In [35]:
import pandas as pd
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import RobustScaler

# Under Sampling

In [20]:
data = pd.read_csv(r'./data versions/training_data.csv')
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,406.0,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1
1,472.0,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1
2,4462.0,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93,1
3,6986.0,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,-0.247768,...,0.573574,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,59.00,1
4,7519.0,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,-1.282858,...,-0.379068,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,1.00,1

In [21]:
data['Class'].value_counts()

0    5000
1     492
Name: Class, dtype: int64

In [22]:
ros = RandomUnderSampler(random_state=10)
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values


xresampled, y_resampled = ros.fit_resample(x, y)

In [23]:
datay = pd.DataFrame(y_resampled)
datax = pd.DataFrame(xresampled)

data_under= pd.concat([datax, datay], axis=1)

In [24]:
data_under.head()

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,0
0,42272.0,-0.135074,1.259648,0.772853,0.434205,1.265065,-0.540877,1.332293,-0.633369,-0.349485,...,-0.110284,0.053994,-0.470305,-0.545631,0.326723,-0.388692,-0.398205,-0.397855,1.00,0
1,77655.0,-1.457450,1.755637,0.870120,-0.142324,-0.550145,-1.008726,0.313781,0.401606,0.045030,...,-0.281567,-0.692184,0.070191,0.348259,-0.021652,0.088106,0.454261,0.250642,8.91,0
2,134327.0,-0.992711,1.242980,0.515756,1.096445,-0.319439,0.442529,-0.293589,1.047119,-0.307031,...,-0.279794,-0.851904,0.167023,-0.462283,-0.790381,-1.010782,-0.096047,0.042029,18.10,0
3,72145.0,-0.459697,0.895863,1.550639,-0.266452,0.203062,-0.373660,0.719435,-0.099588,-0.273696,...,-0.243452,-0.594471,-0.090176,-0.048181,-0.248232,0.036520,-0.044536,-0.120046,1.98,0
4,133341.0,1.892957,0.274218,-0.952597,3.620675,0.704423,0.764848,0.001309,0.129675,-0.731241,...,0.067699,0.265363,-0.069800,-1.056774,0.208681,0.140523,-0.040175,-0.068328,30.31,0

In [25]:
data_under.columns = data.columns

In [31]:
rs_time = RobustScaler()
rs_amount = RobustScaler()
data_under['Amount'] = rs_amount.fit_transform(data_under['Amount'].values.reshape(-1, 1))
data_under['Time'] = rs_time.fit_transform(data_under['Time'].values.reshape(-1,1))

In [33]:
data_under.to_csv('data_under.csv', index=False)

# Over Sampling

In [36]:
oversample = SMOTE()
data = pd.read_csv(r'./data versions/training_data.csv')
rs_time = RobustScaler()
rs_amount = RobustScaler()
data['Amount'] = rs_amount.fit_transform(data['Amount'].values.reshape(-1, 1))
data['Time'] = rs_time.fit_transform(data['Time'].values.reshape(-1,1))
x, y = data.iloc[:,:-1].values, data.iloc[:, -1].values

x, y = oversample.fit_resample(x,y)

In [42]:
datay = pd.DataFrame(y)
datax = pd.DataFrame(x)
data_over =  pd.concat([datax, datay], axis=1)
data_over.columns = data.columns
data_over.to_csv('data_over.csv', index=False, header=data.columns)

In [43]:
data_over.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-0.952734,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,-0.279403,1
1,-0.951963,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,6.707324,1
2,-0.905356,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,2.889454,1
3,-0.875874,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,-0.247768,...,0.573574,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,0.499835,1
4,-0.869648,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,-1.282858,...,-0.379068,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,-0.266196,1